// @ts-check
import fs from 'fs';
import path from 'path';

/**
 * Filter autogenerated sidebar items to only include files that actually exist in the current locale directory.
 */
function getLocaleSidebar(locale) {
  // If locale is default (ko), use full autogenerated sidebar
  if (!locale || locale === 'ko') {
    return [{ type: 'autogenerated', dirName: '.' }];
  }

  // For 'en', autogenerate based on what actually exists in i18n/en directory
  return [{ type: 'autogenerated', dirName: '.' }];
}

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  tutorialSidebar: [{ type: 'autogenerated', dirName: '.' }],
};

export default sidebars;
